directory: ~/music
library: ~/music/musiclibrary.db
import:
  move: yes
  write: yes
  log: beetslog.txt
art_filename: cover 
pluginpath: ~/beets/myplugins
ui:
  color: yes

paths:
  default: albums/$albumartist/[$original_year] $album%aunique{}/$track $title
  singleton: singles/$artist/$title
  comp: compilations/[$original_year] $album%aunique{}/$track $title
