no-keepaspect-window
no-border
save-position-on-quit
hwdec=auto

sub-font='AktivGrotesk-Regular'
sub-border-size=2
sub-color='#d7d7d7' #subtitle color in rgb
sub-shadow-color='#000000' #shadow color 
sub-bold=yes
sub-font-size=60
sub-pos=95
sub-blur=0.3

