# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family        Iosevka Term

font_size 13.0

cursor #007ACC

cursor_text_color #FFFFFF

remember_window_size  no 

window_border_width 1.0

window_padding_width 6

hide_window_decorations yes

foreground #000000

background #F7F7F7

selection_background #BFDBFE

#: The 16 terminal colors.

color0 #000000
color8 #777777

#: black

color1 #AA3731
color9 #F05050

#: red

color2  #448C27
color10 #60CB00

#: green

color3  #CB9000
color11 #FFBC5D

#: yellow

color4  #325CC0
color12 #007ACC

#: blue

color5  #7A3E9D
color13 #E64CE6

#: magenta

color6  #0083B2
color14 #00AACB

#: cyan

color7  #AAAAAA
color15 #FFFFFF

term xterm-kitty

